name: Build result

on:
  schedule:
  - cron:  '0 8 * * *'
  push:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.x

    - name: Clone latest clash
      run: |
        git clone https://github.com/Dreamacro/clash.git
        git clone https://github.com/Dreamacro/go-shadowsocks2.git

    - name: Patch files
      run: |
        patch -p0 <patchs/0000-go-shadowsocks2-add-clash.diff
        patch -p0 <patchs/0001-clash-rewrite-go-mod.diff

    - name: Build clash all platform
      run: |
        cd clash
        make all-arch

    - name: Release files
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |  
        set -x
        hub release delete latest | true
        hub release create -m latest latest
        UPSTREAM_HASH=`cd clash && git rev-parse HEAD`
        
        for item in `ls clash/bin`; do
          gzip -9 clash/bin/$item
          hub release edit -a clash/bin/$item.gz -m "" latest
        done

        pushd clash/bin
        sha256sum * > sha256sum
        popd

        hub release edit -a clash/bin/sha256sum -m "" latest
        echo ${{github.sha}} > github.release
        echo "" >> github.release
        echo "Upstream Hash: \`$UPSTREAM_HASH\`" >> github.release
        echo "" >> github.release
        echo "\`\`\`" >> github.release
        cat clash/bin/sha256sum >> github.release
        echo "\`\`\`" >> github.release
        hub release edit -F github.release latest