name: Build result

on:
  push:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.x

    - name: Clone latest clash
      run: |
        git clone https://github.com/Dreamacro/clash.git
        git clone https://github.com/Dreamacro/go-shadowsocks2.git

    - name: Patch files
      run: |
        patch -p0 <patchs/0000-go-shadowsocks2-add-clash.diff
        patch -p0 <patchs/0001-clash-rewrite-go-mod.diff

    - name: Build clash all platform
      run: |
        cd clash
        make all-arch

    - name: Release files
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |  
        set -x
        assets=()
        for asset in clash/bin/*; do
          assets+=("-a" "$asset")
        done
        hub release delete latest
        hub release create "${assets[@]}" -m latest latest